micronaut:
  application:
    name: inversiones

  server:
    cors:
      enabled: true
#    netty:
#      worker:
#        threads: 2
#      parent:
#        threads: 2
#      childOptions:
#        autoRead: true
io:
  watch:
    paths: src/main
    restart: true
#executors:
#  io:
#    type: fixed
#    nThreads: 1

dataSource:
  url: "jdbc:mysql://localhost:3306/inversiones?autoReconnect=true&useSSL=false"
  driverClassName: "com.mysql.cj.jdbc.Driver"
  username: "wc_bluesky_dev"
  password: "wc_bluesky_dev"
  #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  #driverClassName: org.h2.Driver
  #username: sa
  #password: ''
  #pooled: true
  #jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
logger:
  levels:
    core.rest: DEBUG
    core.query: DEBUG
    org.hibernate.orm.deprecation: ERROR

    agregaciones.controllers: DEBUG

    cotizaciones.controllers: DEBUG
    cotizaciones.services: DEBUG

    inversiones.controllers: DEBUG
    inversiones.services: DEBUG
